repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.2.1
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.4.11
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.4.11"]
        files: ^frontend/
