services:
  db:
    ports:
      - "5432:5432"

  mosquitto:
    ports:
      - "1883:1883"

  backend:
    command: sh -c "uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./docs:/docs
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
    ports:
      - "8000:8000"
