"""add berth invitation table

Revision ID: 51a9521408a9
Revises: da492cf8c15a
Create Date: 2026-05-12 13:41:47.916085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a9521408a9'
down_revision: Union[str, Sequence[str], None] = 'da492cf8c15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berth_invites',
    sa.Column('invite_id', sa.String(), nullable=False),
    sa.Column('berth_id', sa.String(), nullable=False),
    sa.Column('harbor_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', 'revoked', 'rejected', name='berth_invite_status'), nullable=False),
    sa.Column('accepted_by', sa.String(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.berth_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['harbor_id'], ['harbors.harbor_id'], ),
    sa.PrimaryKeyConstraint('invite_id')
    )
    op.drop_index(op.f('ix_user_verifications_token'), table_name='user_verifications')
    op.create_index(op.f('ix_user_verifications_token'), 'user_verifications', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_verifications_token'), table_name='user_verifications')
    op.create_index(op.f('ix_user_verifications_token'), 'user_verifications', ['token'], unique=True)
    op.drop_table('berth_invites')
    # ### end Alembic commands ###
