"""initial schema

Revision ID: 60d110ea711d
Revises: 
Create Date: 2026-04-17 08:31:17.322219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d110ea711d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harbors',
    sa.Column('harbor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lng', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('harbor_id')
    )
    op.create_table('docks',
    sa.Column('dock_id', sa.String(), nullable=False),
    sa.Column('harbor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['harbor_id'], ['harbors.harbor_id'], ),
    sa.PrimaryKeyConstraint('dock_id')
    )
    op.create_table('berths',
    sa.Column('berth_id', sa.String(), nullable=False),
    sa.Column('dock_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('length_m', sa.Double(), nullable=True),
    sa.Column('width_m', sa.Double(), nullable=True),
    sa.Column('depth_m', sa.Double(), nullable=True),
    sa.Column('status', sa.Enum('free', 'occupied', name='berth_status'), nullable=False),
    sa.Column('sensor_raw', sa.Integer(), nullable=True),
    sa.Column('battery_pct', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.dock_id'], ),
    sa.PrimaryKeyConstraint('berth_id')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('berth_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('unauthorized_mooring', 'sensor_offline', 'low_battery', name='alert_type'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.berth_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('berth_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('occupied', 'freed', 'alert_unauthorized', 'heartbeat', name='event_type'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.berth_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('events')
    op.drop_table('alerts')
    op.drop_table('berths')
    op.drop_table('docks')
    op.drop_table('harbors')
    sa.Enum(name='event_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='alert_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='berth_status').drop(op.get_bind(), checkfirst=False)
