"""modify assignment table

Revision ID: 9ff8773b91b4
Revises: fafb793abfb5
Create Date: 2026-05-01 21:48:19.778224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ff8773b91b4'
down_revision: Union[str, Sequence[str], None] = 'fafb793abfb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('is_reserved', sa.Boolean(), nullable=False))
    op.add_column('assignments', sa.Column('berth_assignment_status', sa.Enum('occupied', 'free', name='berth_assignment_status'), nullable=False))
    op.drop_constraint(op.f('assignments_berth_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_user_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignments', 'berths', ['berth_id'], ['berth_id'], ondelete='CASCADE')
    op.drop_column('assignments', 'assigned_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_user_id_fkey'), 'assignments', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('assignments_berth_id_fkey'), 'assignments', 'berths', ['berth_id'], ['berth_id'])
    op.drop_column('assignments', 'berth_assignment_status')
    op.drop_column('assignments', 'is_reserved')
    # ### end Alembic commands ###
