"""add assignment table

Revision ID: fafb793abfb5
Revises: f7a83c1d9e02
Create Date: 2026-05-01 20:37:39.012987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fafb793abfb5'
down_revision: Union[str, Sequence[str], None] = 'f7a83c1d9e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('berth_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.berth_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('berth_id')
    )
    op.drop_index(op.f('ix_nodes_berth_active'), table_name='nodes', postgresql_where="(status <> 'decommissioned'::node_status)")
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.create_index(op.f('ix_nodes_berth_active'), 'nodes', ['berth_id'], unique=True, postgresql_where="(status <> 'decommissioned'::node_status)")
    op.drop_table('assignments')
    # ### end Alembic commands ###
