import asyncio
import contextlib
import logging
import time
import uuid
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from datetime import UTC, datetime, timedelta

from fastapi import Depends, FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import JSONResponse
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from sqlalchemy import func, select, text
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.types import ASGIApp, Receive, Scope, Send

from app.adoption.sweeper import sweeper_loop
from app.auth import require_csrf
from app.config import get_settings
from app.db import get_engine, get_sessionmaker
from app.logging_config import request_id_var, setup_logging
from app.models import AdoptionRequest, Gateway
from app.mqtt import is_mqtt_connected, mqtt_listener
from app.rate_limit import limiter
from app.routers import (
    admin,
    adoptions,
    auth,
    berths,
    docks,
    gateways,
    harbors,
    nodes,
    users,
)
from app.schemas import HealthStatus

setup_logging()


# /api/.../stream paths are SSE so skip gzip buffering
def _is_sse_path(path: str) -> bool:
    return path.startswith("/api/") and path.endswith("/stream")


class GZipExceptStream:
    """GZip wrapper that bypasses SSE endpoints — gzip buffers chunks, which
    delays event delivery on long-lived text/event-stream responses."""

    def __init__(self, app: ASGIApp, *, minimum_size: int = 1024) -> None:
        self._app = app
        self._gzip = GZipMiddleware(app, minimum_size=minimum_size)

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] == "http" and _is_sse_path(scope.get("path", "")):
            await self._app(scope, receive, send)
            return
        await self._gzip(scope, receive, send)


_start_time = time.monotonic()
logger = logging.getLogger(__name__)
access_logger = logging.getLogger("app.access")

API_DESCRIPTION = """\
REST API for the DockPulse harbor berth availability system.

The OpenAPI document at `/openapi.json` (and the YAML mirror in
`docs/api/openapi.yml`) is generated directly from these route
definitions and Pydantic models. The committed YAML is regenerated by
`scripts/dump_openapi.py` and CI fails on drift.
"""

TAGS_METADATA = [
    {"name": "system", "description": "System health and status"},
    {"name": "berths", "description": "Berth monitoring and live updates"},
    {"name": "docks", "description": "Dock listing and detail"},
    {"name": "auth", "description": "Registration, login, logout"},
    {"name": "users", "description": "User profile and preferences"},
    {"name": "adoptions", "description": "Node adoption requests"},
    {"name": "gateways", "description": "Gateway listing and status"},
    {"name": "nodes", "description": "Adopted node inventory and lifecycle"},
    {
        "name": "admin",
        "description": (
            "Admin endpoints for the per-env panel at admin.<env>.dockpulse.xyz; "
            "auth is Cloudflare Access (Cf-Access-Jwt-Assertion header)"
        ),
    },
]

SERVERS = [
    {"url": "http://localhost:8000", "description": "Local development"},
    {"url": "https://staging.example.com", "description": "Staging"},
]


def _log_task_exception(task: asyncio.Task) -> None:
    if task.cancelled():
        return
    exc = task.exception()
    if exc is not None:
        logger.error("background task %s crashed", task.get_name(), exc_info=exc)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    tasks = [
        asyncio.create_task(mqtt_listener(), name="mqtt_listener"),
        asyncio.create_task(sweeper_loop(), name="adoption_sweeper"),
    ]
    for task in tasks:
        task.add_done_callback(_log_task_exception)
    yield
    for task in tasks:
        task.cancel()
    for task in tasks:
        with contextlib.suppress(asyncio.CancelledError):
            await task


class RequestContextMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        rid = request.headers.get("x-request-id") or uuid.uuid4().hex
        token = request_id_var.set(rid)
        start = time.perf_counter()
        try:
            response = await call_next(request)
        except Exception:
            duration_ms = (time.perf_counter() - start) * 1000
            access_logger.exception(
                "%s %s -> 500 (%.1fms)",
                request.method,
                request.url.path,
                duration_ms,
            )
            request_id_var.reset(token)
            raise
        duration_ms = (time.perf_counter() - start) * 1000
        response.headers["x-request-id"] = rid
        access_logger.info(
            "%s %s -> %d (%.1fms)",
            request.method,
            request.url.path,
            response.status_code,
            duration_ms,
        )
        request_id_var.reset(token)
        return response


app = FastAPI(
    title="DockPulse API",
    description=API_DESCRIPTION,
    version="0.1.0",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_tags=TAGS_METADATA,
    servers=SERVERS,
    lifespan=lifespan,
    # double-submit csrf check on every non-safe method, dep no-ops on GET/HEAD/OPTIONS
    dependencies=[Depends(require_csrf)],
)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(RequestContextMiddleware)
app.add_middleware(GZipExceptStream, minimum_size=1024)

# CORS only needed in prod, dev runs same-origin via vite proxy
_cors_origins = get_settings().cors_allowed_origins
if _cors_origins:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=_cors_origins,
        allow_credentials=True,
        allow_methods=["GET", "POST", "PATCH", "PUT", "DELETE", "OPTIONS"],
        allow_headers=["Authorization", "Content-Type", "X-Request-ID"],
        expose_headers=["X-Request-ID"],
        max_age=600,
    )

app.include_router(admin.router)
app.include_router(adoptions.router)
app.include_router(auth.router)
app.include_router(berths.router)
app.include_router(docks.router)
app.include_router(harbors.router)
app.include_router(gateways.router)
app.include_router(nodes.router)
app.include_router(users.router)


@app.get(
    "/api/health",
    tags=["system"],
    operation_id="getHealth",
    summary="Health check",
    response_model=HealthStatus,
    responses={
        503: {
            "description": (
                "Service is degraded — at least one dependency is unreachable"
            ),
            "model": HealthStatus,
        }
    },
)
async def health():
    db_ok = True
    try:
        async with get_engine().connect() as conn:
            await conn.execute(text("SELECT 1"))
    except Exception:
        db_ok = False

    mqtt_ok = is_mqtt_connected()

    # adoption + gateway counters help oncall spot a degraded pipeline at a glance
    gateways_online = gateways_total = pending = err_last_15min = 0
    if db_ok:
        try:
            async with get_sessionmaker()() as session:
                gateways_total = (
                    await session.scalar(select(func.count()).select_from(Gateway))
                ) or 0
                gateways_online = (
                    await session.scalar(
                        select(func.count())
                        .select_from(Gateway)
                        .where(Gateway.status == "online")
                    )
                ) or 0
                pending = (
                    await session.scalar(
                        select(func.count())
                        .select_from(AdoptionRequest)
                        .where(AdoptionRequest.status == "pending")
                    )
                ) or 0
                cutoff = datetime.now(UTC) - timedelta(minutes=15)
                err_last_15min = (
                    await session.scalar(
                        select(func.count())
                        .select_from(AdoptionRequest)
                        .where(
                            AdoptionRequest.status == "err",
                            AdoptionRequest.completed_at >= cutoff,
                        )
                    )
                ) or 0
        except Exception:
            db_ok = False

    status = "ok" if db_ok and mqtt_ok else "degraded"

    return JSONResponse(
        status_code=200 if status == "ok" else 503,
        content={
            "status": status,
            "uptime": time.monotonic() - _start_time,
            "database": "ok" if db_ok else "error",
            "mqtt": "ok" if mqtt_ok else "error",
            "gateways_online": gateways_online,
            "gateways_total": gateways_total,
            "adoption": {
                "pending": pending,
                "err_last_15min": err_last_15min,
            },
        },
    )
