/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/adoptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an adoption request for a scanned node */
        post: operations["createAdoption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adoptions/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an adoption request by id */
        get: operations["getAdoption"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adoptions/{request_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a pending adoption request */
        post: operations["cancelAdoption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adoptions/{request_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to adoption progress via Server-Sent Events
         * @description Opens a long-lived `text/event-stream` for a single adoption request. The first frame is a snapshot of the current state. Subsequent frames are `AdoptionUpdateEvent`s emitted when the gateway reports back. The stream closes once the request reaches a terminal state (`ok` or `err`).
         */
        get: operations["streamAdoption"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and set session cookies */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate all tokens for the current user */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh cookie and reissue the access cookie */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all berths */
        get: operations["listBerths"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berths/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List availability windows in a harbor */
        get: operations["listHarborAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berths/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to live berth updates via Server-Sent Events
         * @description Opens a long-lived `text/event-stream` connection. Each message is a JSON-encoded `BerthUpdateEvent`. Clients should first fetch a snapshot via `GET /api/berths` and then merge streamed updates by `berth_id`. Reconnects re-subscribe but do not replay missed events — re-fetch the snapshot after an `open` that follows a disconnection.
         */
        get: operations["streamBerths"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berths/{berth_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single berth */
        get: operations["getBerth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berths/{berth_id}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign a berth to a user */
        put: operations["assignBerth"];
        post?: never;
        /** Remove a berth assignment */
        delete: operations["removeBerthAssignment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berths/{berth_id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List availability windows for a berth */
        get: operations["listBerthAvailability"];
        put?: never;
        /** Create an availability window for a berth */
        post: operations["createBerthAvailability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berths/{berth_id}/availability/{window_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an availability window */
        delete: operations["deleteBerthAvailability"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berths/{berth_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events for a berth */
        get: operations["listBerthEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all docks */
        get: operations["listDocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docks/{dock_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single dock with its berths */
        get: operations["getDock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gateways": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gateways visible to the harbormaster */
        get: operations["listGateways"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all harbors */
        get: operations["listHarbors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List nodes with derived health */
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get node detail with recent telemetry */
        get: operations["getNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node_id}/decommission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark node as decommissioned */
        post: operations["decommissionNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /** Delete the current boat-owner account */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /** Update current user profile */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/users/me/notification-prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get notification preferences for the current user */
        get: operations["getNotificationPrefs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update notification preferences for the current user */
        patch: operations["updateNotificationPrefs"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdoptIn */
        AdoptIn: {
            /**
             * Berth Id
             * @example berth-001
             */
            berth_id: string;
            /**
             * Gateway Id
             * @example gw-dock-a
             */
            gateway_id: string;
            /**
             * Qr Payload
             * @description Base64url-encoded JSON from QR fragment (uuid, oob, sn, jwt)
             */
            qr_payload: string;
        };
        /** AdoptionRequestOut */
        AdoptionRequestOut: {
            /**
             * Berth Id
             * @example berth-001
             */
            berth_id: string;
            /**
             * Completed At
             * @example 2026-05-03T14:31:00Z
             */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             * @example 2026-05-03T14:30:00Z
             */
            created_at: string;
            /**
             * Error Code
             * @example timeout
             */
            error_code?: string | null;
            /**
             * Error Msg
             * @example node did not respond
             */
            error_msg?: string | null;
            /**
             * Expires At
             * Format: date-time
             * @example 2026-05-03T14:35:00Z
             */
            expires_at: string;
            /**
             * Gateway Id
             * @example gw-dock-a
             */
            gateway_id: string;
            /**
             * Mesh Unicast Addr
             * @example 0x0042
             */
            mesh_unicast_addr?: string | null;
            /**
             * Mesh Uuid
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            mesh_uuid: string;
            /**
             * Request Id
             * @example req-0001
             */
            request_id: string;
            /**
             * Serial Number
             * @example DP-N-000123
             */
            serial_number: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "ok" | "err";
        };
        /** AdoptionUpdateEvent */
        AdoptionUpdateEvent: {
            request: components["schemas"]["AdoptionRequestOut"];
            /**
             * Type
             * @default adoption.update
             * @constant
             */
            type: "adoption.update";
        };
        /** AssignBerthIn */
        AssignBerthIn: {
            /**
             * User Id
             * @example user-001
             */
            user_id: string;
        };
        /** AssignmentOut */
        AssignmentOut: {
            /**
             * Berth Id
             * @example berth-001
             */
            berth_id: string;
            /**
             * User Id
             * @example user-001
             */
            user_id: string;
        };
        /** BerthAvailabilityWindowIn */
        BerthAvailabilityWindowIn: {
            /**
             * From Date
             * Format: date-time
             * @example 2026-06-01T00:00:00Z
             */
            from_date: string;
            /**
             * Return Date
             * Format: date-time
             * @example 2026-06-08T00:00:00Z
             */
            return_date: string;
        };
        /** BerthAvailabilityWindowOut */
        BerthAvailabilityWindowOut: {
            /**
             * Berth Id
             * @example berth-001
             */
            berth_id: string;
            /**
             * Created At
             * Format: date-time
             * @example 2026-05-05T14:30:00Z
             */
            created_at: string;
            /**
             * From Date
             * Format: date-time
             * @example 2026-06-01T00:00:00Z
             */
            from_date: string;
            /**
             * Return Date
             * Format: date-time
             * @example 2026-06-08T00:00:00Z
             */
            return_date: string;
            /**
             * User Id
             * @example user-001
             */
            user_id: string;
            /**
             * Window Id
             * @example win-0001
             */
            window_id: string;
        };
        /** BerthOut */
        BerthOut: {
            assignment?: components["schemas"]["AssignmentOut"] | null;
            /**
             * Battery Pct
             * @example 87
             */
            battery_pct?: number | null;
            /**
             * Berth Id
             * @example berth-001
             */
            berth_id: string;
            /**
             * Depth M
             * @example 2
             */
            depth_m?: number | null;
            /**
             * Dock Id
             * @example dock-a
             */
            dock_id: string;
            /**
             * Is Reserved
             * @default false
             */
            is_reserved: boolean;
            /**
             * Label
             * @example A1
             */
            label?: string | null;
            /**
             * Last Updated
             * @example 2026-05-03T14:30:00Z
             */
            last_updated?: string | null;
            /**
             * Length M
             * @example 8.5
             */
            length_m?: number | null;
            /**
             * Sensor Raw
             * @example 1234
             */
            sensor_raw?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "free" | "occupied";
            /**
             * Width M
             * @example 3.2
             */
            width_m?: number | null;
        };
        /** BerthUpdateEvent */
        BerthUpdateEvent: {
            berth: components["schemas"]["BerthOut"];
            /**
             * Type
             * @default berth.update
             * @constant
             */
            type: "berth.update";
        };
        /** DockOut */
        DockOut: {
            /**
             * Dock Id
             * @example dock-a
             */
            dock_id: string;
            /**
             * Harbor Id
             * @example harbor-saltsjobaden
             */
            harbor_id: string;
            /**
             * Name
             * @example A Pier
             */
            name: string;
        };
        /** DockWithBerthsOut */
        DockWithBerthsOut: {
            /**
             * Berths
             * @default []
             */
            berths: components["schemas"]["BerthOut"][];
            /**
             * Dock Id
             * @example dock-a
             */
            dock_id: string;
            /**
             * Harbor Id
             * @example harbor-saltsjobaden
             */
            harbor_id: string;
            /**
             * Name
             * @example A Pier
             */
            name: string;
        };
        /** EventOut */
        EventOut: {
            /**
             * Berth Id
             * @example berth-001
             */
            berth_id: string;
            /**
             * Event Id
             * @example evt-0001
             */
            event_id: string;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "occupied" | "freed" | "alert_unauthorized" | "heartbeat";
            /**
             * Node Id
             * @example node-012
             */
            node_id: string;
            /**
             * Sensor Raw
             * @example 1234
             */
            sensor_raw: number;
            /**
             * Timestamp
             * Format: date-time
             * @example 2026-05-03T14:30:00Z
             */
            timestamp: string;
        };
        /** GatewayOut */
        GatewayOut: {
            /**
             * Dock Id
             * @example dock-a
             */
            dock_id: string;
            /**
             * Gateway Id
             * @example gw-dock-a
             */
            gateway_id: string;
            /**
             * Last Seen
             * @example 2026-05-03T14:30:00Z
             */
            last_seen?: string | null;
            /**
             * Name
             * @example Pier A gateway
             */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "online" | "offline";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HarborOut */
        HarborOut: {
            /**
             * Harbor Id
             * @example harbor-saltsjobaden
             */
            harbor_id: string;
            /**
             * Name
             * @example Saltsjöbaden Marina
             */
            name: string;
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /**
             * Mqtt
             * @enum {string}
             */
            mqtt: "ok" | "error";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Uptime
             * @example 12345.6
             */
            uptime: number;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             * @example alex@example.com
             */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** NodeDetailOut */
        NodeDetailOut: {
            /**
             * Adopted At
             * Format: date-time
             * @example 2026-05-03T14:00:00Z
             */
            adopted_at: string;
            /**
             * Battery Pct
             * @example 87
             */
            battery_pct?: number | null;
            /**
             * Berth Id
             * @example berth-001
             */
            berth_id: string;
            /**
             * Gateway Id
             * @example gw-dock-a
             */
            gateway_id: string;
            /**
             * Health
             * @enum {string}
             */
            health: "online" | "stale" | "offline" | "decommissioned";
            /**
             * Last Seen
             * @example 2026-05-03T14:30:00Z
             */
            last_seen?: string | null;
            /**
             * Mesh Unicast Addr
             * @example 0x0042
             */
            mesh_unicast_addr: string;
            /**
             * Node Id
             * @example node-012
             */
            node_id: string;
            /**
             * Recent Events
             * @default []
             */
            recent_events: components["schemas"]["EventOut"][];
            /**
             * Serial Number
             * @example DP-N-000123
             */
            serial_number: string;
        };
        /** NodeHealthOut */
        NodeHealthOut: {
            /**
             * Adopted At
             * Format: date-time
             * @example 2026-05-03T14:00:00Z
             */
            adopted_at: string;
            /**
             * Battery Pct
             * @example 87
             */
            battery_pct?: number | null;
            /**
             * Berth Id
             * @example berth-001
             */
            berth_id: string;
            /**
             * Gateway Id
             * @example gw-dock-a
             */
            gateway_id: string;
            /**
             * Health
             * @enum {string}
             */
            health: "online" | "stale" | "offline" | "decommissioned";
            /**
             * Last Seen
             * @example 2026-05-03T14:30:00Z
             */
            last_seen?: string | null;
            /**
             * Mesh Unicast Addr
             * @example 0x0042
             */
            mesh_unicast_addr: string;
            /**
             * Node Id
             * @example node-012
             */
            node_id: string;
            /**
             * Serial Number
             * @example DP-N-000123
             */
            serial_number: string;
        };
        /** NotificationPrefsOut */
        NotificationPrefsOut: {
            /** Notify Arrival */
            notify_arrival: boolean;
            /** Notify Departure */
            notify_departure: boolean;
        };
        /** NotificationPrefsPatch */
        NotificationPrefsPatch: {
            /** Notify Arrival */
            notify_arrival?: boolean | null;
            /** Notify Departure */
            notify_departure?: boolean | null;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Boat Club
             * @example Saltsjöbadens BK
             */
            boat_club?: string | null;
            /**
             * Email
             * Format: email
             * @example alex@example.com
             */
            email: string;
            /**
             * Firstname
             * @example Alex
             */
            firstname: string;
            /**
             * Lastname
             * @example Alex
             */
            lastname: string;
            /**
             * Password
             * Format: password
             * @example correct horse battery staple
             */
            password: string;
            /**
             * Phone
             * @example +46 70 123 45 67
             */
            phone?: string | null;
        };
        /** UserOut */
        UserOut: {
            /**
             * Assigned Berth Id
             * @example berth-001
             */
            assigned_berth_id?: string | null;
            /**
             * Boat Club
             * @example Saltsjöbadens BK
             */
            boat_club?: string | null;
            /**
             * Email
             * Format: email
             * @example alex@example.com
             */
            email: string;
            /**
             * Firstname
             * @example Alex
             */
            firstname: string;
            /**
             * Lastname
             * @example Lindgren
             */
            lastname: string;
            /**
             * Phone
             * @example +46 70 123 45 67
             */
            phone?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "harbormaster" | "boat_owner";
            /**
             * User Id
             * @example user-001
             */
            user_id: string;
        };
        /** UserPatch */
        UserPatch: {
            /**
             * Boat Club
             * @example Saltsjöbadens BK
             */
            boat_club?: string | null;
            /** Current Password */
            current_password?: string | null;
            /**
             * Email
             * @example alex@example.com
             */
            email?: string | null;
            /**
             * Firstname
             * @example Alex
             */
            firstname?: string | null;
            /**
             * Lastname
             * @example Alex
             */
            lastname?: string | null;
            /**
             * Password
             * @example correct horse battery staple
             */
            password?: string | null;
            /**
             * Phone
             * @example +46 70 123 45 67
             */
            phone?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAdoption: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdoptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdoptionRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getAdoption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdoptionRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelAdoption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdoptionRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    streamAdoption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Each frame is a JSON-encoded AdoptionUpdateEvent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdoptionUpdateEvent"];
                };
            };
            /** @description Adoption request not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                dockpulse_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listBerths: {
        parameters: {
            query?: {
                /** @description filter by dock */
                dock_id?: string | null;
                /** @description filter by status */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listHarborAvailability: {
        parameters: {
            query: {
                /** @description harbor to filter on */
                harbor_id: string;
                /** @description windows must end after */
                from_date?: string | null;
                /** @description windows must start before */
                return_date?: string | null;
                length_m?: number | null;
                width_m?: number | null;
                depth_m?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthAvailabilityWindowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    streamBerths: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Each frame is a JSON-encoded BerthUpdateEvent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthUpdateEvent"];
                };
            };
        };
    };
    getBerth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                berth_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assignBerth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                berth_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignBerthIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    removeBerthAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                berth_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listBerthAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                berth_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthAvailabilityWindowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createBerthAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                berth_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BerthAvailabilityWindowIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthAvailabilityWindowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteBerthAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                berth_id: string;
                window_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listBerthEvents: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                berth_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDocks: {
        parameters: {
            query?: {
                /** @description Filter by harbor */
                harbor_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DockOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DockWithBerthsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listGateways: {
        parameters: {
            query?: {
                /** @description Filter by harbor */
                harbor_id?: string | null;
                /** @description Filter by dock */
                dock_id?: string | null;
                /** @description Filter by gateway status */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listHarbors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarborOut"][];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Service is degraded — at least one dependency is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    listNodes: {
        parameters: {
            query?: {
                /** @description Filter by gateway */
                gateway_id?: string | null;
                /** @description Filter by berth */
                berth_id?: string | null;
                /** @description Filter by health */
                health?: ("online" | "stale" | "offline" | "decommissioned") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeHealthOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getNode: {
        parameters: {
            query?: {
                events_limit?: number;
            };
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decommissionNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeHealthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getNotificationPrefs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPrefsOut"];
                };
            };
        };
    };
    updateNotificationPrefs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPrefsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPrefsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
