/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/harbors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all harbors */
    get: operations["listHarbors"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/harbors/{harbor_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single harbor with its docks */
    get: operations["getHarbor"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all docks */
    get: operations["listDocks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docks/{dock_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single dock with its berths */
    get: operations["getDock"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/berths": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all berths */
    get: operations["listBerths"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/berths/{berth_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single berth */
    get: operations["getBerth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/berths/{berth_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get occupancy event history for a berth */
    get: operations["getBerthEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/alerts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List active alerts */
    get: operations["listAlerts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/alerts/{alert_id}/acknowledge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Acknowledge an alert */
    post: operations["acknowledgeAlert"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    BerthStatus: "free" | "occupied";
    Berth: {
      /** @example berth-001 */
      berth_id: string;
      /** @example dock-a */
      dock_id: string;
      /** @example A-01 */
      label?: string;
      /**
       * Format: double
       * @description Berth length in meters
       * @example 12
       */
      length_m?: number;
      /**
       * Format: double
       * @description Berth width in meters
       * @example 4
       */
      width_m?: number;
      /**
       * Format: double
       * @description Water depth in meters
       * @example 2.5
       */
      depth_m?: number;
      status: components["schemas"]["BerthStatus"];
      /** @description Latest raw sensor reading */
      sensor_raw?: number;
      /** @description Node battery level (0-100) */
      battery_pct?: number;
      /** Format: date-time */
      last_updated?: string;
    };
    Harbor: {
      /** @example harbor-stockholm */
      harbor_id: string;
      /** @example Stockholm Harbor */
      name: string;
      /**
       * Format: double
       * @example 59.3293
       */
      lat?: number;
      /**
       * Format: double
       * @example 18.0686
       */
      lng?: number;
    };
    Dock: {
      /** @example dock-a */
      dock_id: string;
      /** @example harbor-stockholm */
      harbor_id: string;
      /** @example North Dock */
      name: string;
    };
    Event: {
      event_id: string;
      berth_id: string;
      /** @description ID of the sensor node that triggered the event */
      node_id: string;
      /** @enum {string} */
      event_type: "occupied" | "freed" | "alert_unauthorized" | "heartbeat";
      /** @description Raw sensor value at time of event */
      sensor_raw: number;
      /** Format: date-time */
      timestamp: string;
    };
    Alert: {
      alert_id: string;
      berth_id: string;
      /** @enum {string} */
      type: "unauthorized_mooring" | "sensor_offline" | "low_battery";
      message: string;
      acknowledged: boolean;
      /** Format: date-time */
      timestamp: string;
    };
    Error: {
      /** @example not_found */
      error: string;
      message: string;
    };
  };
  responses: {
    /** @description Invalid request parameters */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example ok */
            status: string;
            /** @description Uptime in seconds */
            uptime?: number;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      /** @description Service unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  listHarbors: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of harbors */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Harbor"][];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  getHarbor: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        harbor_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Harbor with docks */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Harbor"] & {
            docks?: components["schemas"]["Dock"][];
          };
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  listDocks: {
    parameters: {
      query?: {
        /** @description Filter by harbor */
        harbor_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of docks */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Dock"][];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  getDock: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dock_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dock with berths */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Dock"] & {
            berths?: components["schemas"]["Berth"][];
          };
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  listBerths: {
    parameters: {
      query?: {
        /** @description Filter by dock */
        dock_id?: string;
        /** @description Filter by occupancy status */
        status?: components["schemas"]["BerthStatus"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of berths */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Berth"][];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  getBerth: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        berth_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Berth details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Berth"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  getBerthEvents: {
    parameters: {
      query?: {
        /** @description Return events after this timestamp */
        since?: string;
        limit?: number;
      };
      header?: never;
      path: {
        berth_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Event"][];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  listAlerts: {
    parameters: {
      query?: {
        /** @description Filter by acknowledgement status */
        acknowledged?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of alerts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Alert"][];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  acknowledgeAlert: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        alert_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Alert acknowledged */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Alert"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
}
